#ifndef PROJECT_PARAMS_H
#define PROJECT_PARAMS_H

#define LP_EPSILON 0.000001

#define MAX_CUT_AGE 5
#define MAX_CUT_POOL_SIZE 1000000

#define LOG_LEVEL LOG_LEVEL_INFO

#define ENABLE_COMB_INEQUALITIES

//#define ALLOW_FRACTIONAL_SOLUTIONS

#endif //PROJECT_PARAMS_H
